version: "3.8"
services:
    apache:
        build: .
        container_name: apache
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mysql
        networks:
            - lamp
    
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - lamp
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links: 
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - ./conf/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
        networks:
            - lamp

volumes:
    persistent:
